name: default
create_nuggets: false
create_qrels: false
judge: true
llm_model: gpt-oss-20b
timestamp: '2026-02-25T04:10:27.946440+00:00'
git:
  commit: dfb5cb48b33cf4af17a24f92bdc44c6b871e30d0
  dirty: 'true'
  remote: https://github.com/jarenunzen/auto-judge-starter-kit.git
settings:
  filebase: myjudge
nugget_settings:
  filebase: myjudge
judge_settings:
  filebase: myjudge
qrels_settings:
  filebase: myjudge
